### ISSUE TITLE
The demosaicing tool does not show in the windows version (0.4.0)

### ISSUE THREAD

**Issue by sasoriakasuna** [spillerrec/Overmix#138] opened 2019-07-04 13:54 UTC
I tried to follow up the demosaicing tutorial and i can't do anything because i cant find the options required.

i'm here to ask the demosaicing works with a static image?

Please make a tutorial i literally can't use your software i barely understand the options, and the documentation is very poor.

**Useful information:**
 - Windows 10 Pro 64 bit
 - overmix 0.4.0
 - 32gb intel core i7.

**Comment by spillerrec** [comment] 2019-07-04 15:56
The demosaicing does not work with a static image, it needs multiple images/video-frames of the same scene with different offsets. This is because it manages to extract different information in each image and then reconstructs it. The quality of the demosaicing directly depends on how much hidden information there are in the multiple images/frames, but in return you get the real image back (and I have actually confirmed this by comparing the result against an western uncensored release of the same anime).

To decensor a single static image you need to make up what goes into the censored area based on experience on what tends to be in such areas. Check out [DeepCreamPy](https://github.com/deeppomf/DeepCreamPy) which have been trained a neural network on thousands of anime images to intelligently fill in a censored area. It also have an unofficial demosaic censor mode. Depending on the images the results are decent, so if you can get it running on Windows it is your best bet for static images.

The reason you can't find the options required in the tutorial is because you need 0.4.0 alpha 2 which there currently is not a Windows release for (you would need to compile from the source code). I can create a preview build for you, just let me know within 24 hours from this reply (as I'm about to go on vacation for a week without computer access).

**Comment by sasoriakasuna** [comment] 2019-07-04 17:15
of course i need the build please <3. And thanks for the info :3 i will try to do my best

**Comment by spillerrec** [comment] 2019-07-05 18:26
https://github.com/spillerrec/Overmix/releases/tag/v0.4.0-alpha2
Let me know if it fails to launch because of missing DLLs, it should have everything but I could have missed something. Could you try to drag and drop a MP4 or MKV video file into Overmix and see if it can read it? (Set the amount to non-zero in the dialog which should appear before clicking OK.) Waifu2x is enabled, but it probably crash if you try to add it under "Preprocessing".

**Comment by spillerrec** [comment] 2019-07-19 15:51
Did you get it to work? Let me know if you still have issues or think that the demosaicing tutorial could need improvement.

**Comment by sasoriakasuna** [comment] 2019-07-22 09:52
Actually works like a charm, sometimes the application crash when i drag a video file, but that's not a problem it's working thank you so much <3

**Comment by spillerrec** [comment] 2019-07-23 20:49
That is great, I will be closing this issue then.

There is a known issue with the video importer that it will crash when loading images past the end of the file (e.g. trying to read at the 6 minute mark on a file only 5 minutes long). But if that is not the case and you either have some clues to what could be causing it or you are willing to spend some time to help me find the issue, then you are very welcome to open a new issue.

**Closed by spillerrec** 2019-07-23 20:49 UTC
Labels: question
